'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ConcretePlant.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADD.
        '''</summary>
        Friend Shared ReadOnly Property ADD() As String
            Get
                Return ResourceManager.GetString("ADD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADD COMBINE.
        '''</summary>
        Friend Shared ReadOnly Property ADDCOMBINE() As String
            Get
                Return ResourceManager.GetString("ADDCOMBINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADD NEW.
        '''</summary>
        Friend Shared ReadOnly Property addnew() As String
            Get
                Return ResourceManager.GetString("addnew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NUMBER OF BATCHES.
        '''</summary>
        Friend Shared ReadOnly Property BATCHESNO() As String
            Get
                Return ResourceManager.GetString("BATCHESNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BATCH EXECUTING-.
        '''</summary>
        Friend Shared ReadOnly Property BATCHEXE() As String
            Get
                Return ResourceManager.GetString("BATCHEXE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BATCH VOLUME 1 (M3).
        '''</summary>
        Friend Shared ReadOnly Property BATCHVOL1() As String
            Get
                Return ResourceManager.GetString("BATCHVOL1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BATCH VOLUME 2 (M3).
        '''</summary>
        Friend Shared ReadOnly Property BATCHVOL2() As String
            Get
                Return ResourceManager.GetString("BATCHVOL2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BATCH No.1.
        '''</summary>
        Friend Shared ReadOnly Property BATNO1() As String
            Get
                Return ResourceManager.GetString("BATNO1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BATCH No.2.
        '''</summary>
        Friend Shared ReadOnly Property BATNO2() As String
            Get
                Return ResourceManager.GetString("BATNO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DETAIL.
        '''</summary>
        Friend Shared ReadOnly Property bt_detail() As String
            Get
                Return ResourceManager.GetString("bt_detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EDIT.
        '''</summary>
        Friend Shared ReadOnly Property bt_edit() As String
            Get
                Return ResourceManager.GetString("bt_edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXER.
        '''</summary>
        Friend Shared ReadOnly Property bt_Mixer_ope() As String
            Get
                Return ResourceManager.GetString("bt_Mixer_ope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COMBINE.
        '''</summary>
        Friend Shared ReadOnly Property bt_toCombine() As String
            Get
                Return ResourceManager.GetString("bt_toCombine", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXTURE.
        '''</summary>
        Friend Shared ReadOnly Property bt_toNhapXuat() As String
            Get
                Return ResourceManager.GetString("bt_toNhapXuat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WEIGHING.
        '''</summary>
        Friend Shared ReadOnly Property bt_toWeiPr() As String
            Get
                Return ResourceManager.GetString("bt_toWeiPr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DELETE.
        '''</summary>
        Friend Shared ReadOnly Property btn_del_ope() As String
            Get
                Return ResourceManager.GetString("btn_del_ope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CAN NOT CONNECT TO SERVER.
        '''</summary>
        Friend Shared ReadOnly Property CANTCONNECT() As String
            Get
                Return ResourceManager.GetString("CANTCONNECT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CAN NOT EDIT. OBJECT MAY NOT EXIST.
        '''</summary>
        Friend Shared ReadOnly Property CANTEDIT() As String
            Get
                Return ResourceManager.GetString("CANTEDIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CAN NOT FIND OBJECT.
        '''</summary>
        Friend Shared ReadOnly Property CANTFINDOBJ() As String
            Get
                Return ResourceManager.GetString("CANTFINDOBJ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CAN NOT WRITE. OBJECT ALREADY EXISTS.
        '''</summary>
        Friend Shared ReadOnly Property CANTWRITE() As String
            Get
                Return ResourceManager.GetString("CANTWRITE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CAR No..
        '''</summary>
        Friend Shared ReadOnly Property CARNO() As String
            Get
                Return ResourceManager.GetString("CARNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COMBINE CODE.
        '''</summary>
        Friend Shared ReadOnly Property CBNCODE() As String
            Get
                Return ResourceManager.GetString("CBNCODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COMPLETION RANGE.
        '''</summary>
        Friend Shared ReadOnly Property ComRANG() As String
            Get
                Return ResourceManager.GetString("ComRANG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COMPLETION TIME.
        '''</summary>
        Friend Shared ReadOnly Property ComTIME() As String
            Get
                Return ResourceManager.GetString("ComTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DO YOU WANT TO DELETE THE ORDER.
        '''</summary>
        Friend Shared ReadOnly Property DELWARR() As String
            Get
                Return ResourceManager.GetString("DELWARR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMS_CPT_RANGE.
        '''</summary>
        Friend Shared ReadOnly Property EMS() As String
            Get
                Return ResourceManager.GetString("EMS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FINE WEIGHING.
        '''</summary>
        Friend Shared ReadOnly Property FINE_WEI() As String
            Get
                Return ResourceManager.GetString("FINE_WEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FLUSHING TIME.
        '''</summary>
        Friend Shared ReadOnly Property FLUSHTIME() As String
            Get
                Return ResourceManager.GetString("FLUSHTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BATCH.
        '''</summary>
        Friend Shared ReadOnly Property FRM_BATCH() As String
            Get
                Return ResourceManager.GetString("FRM_BATCH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OPERATE.
        '''</summary>
        Friend Shared ReadOnly Property frm_operate() As String
            Get
                Return ResourceManager.GetString("frm_operate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GATE CLOSE TIME.
        '''</summary>
        Friend Shared ReadOnly Property GaClsTi() As String
            Get
                Return ResourceManager.GetString("GaClsTi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LANGUAGE.
        '''</summary>
        Friend Shared ReadOnly Property gb_lang() As String
            Get
                Return ResourceManager.GetString("gb_lang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HOPPER CHECK TIME.
        '''</summary>
        Friend Shared ReadOnly Property HopCT() As String
            Get
                Return ResourceManager.GetString("HopCT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JOG OFF.
        '''</summary>
        Friend Shared ReadOnly Property JOGOFF() As String
            Get
                Return ResourceManager.GetString("JOGOFF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JOG TIME.
        '''</summary>
        Friend Shared ReadOnly Property JOGON() As String
            Get
                Return ResourceManager.GetString("JOGON", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SETTING.
        '''</summary>
        Friend Shared ReadOnly Property lb_setting_ope() As String
            Get
                Return ResourceManager.GetString("lb_setting_ope", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property LB136WEI() As String
            Get
                Return ResourceManager.GetString("LB136WEI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXER CHECK TIME.
        '''</summary>
        Friend Shared ReadOnly Property MCheckT() As String
            Get
                Return ResourceManager.GetString("MCheckT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXER EMPTY TIME.
        '''</summary>
        Friend Shared ReadOnly Property MEmptyT() As String
            Get
                Return ResourceManager.GetString("MEmptyT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXER GATE OPEN TIME.
        '''</summary>
        Friend Shared ReadOnly Property MGateOT() As String
            Get
                Return ResourceManager.GetString("MGateOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 1.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME1() As String
            Get
                Return ResourceManager.GetString("MIX_TIME1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 10.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME10() As String
            Get
                Return ResourceManager.GetString("MIX_TIME10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 2.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME2() As String
            Get
                Return ResourceManager.GetString("MIX_TIME2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 3.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME3() As String
            Get
                Return ResourceManager.GetString("MIX_TIME3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 4.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME4() As String
            Get
                Return ResourceManager.GetString("MIX_TIME4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 5.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME5() As String
            Get
                Return ResourceManager.GetString("MIX_TIME5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 6.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME6() As String
            Get
                Return ResourceManager.GetString("MIX_TIME6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 7.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME7() As String
            Get
                Return ResourceManager.GetString("MIX_TIME7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 8.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME8() As String
            Get
                Return ResourceManager.GetString("MIX_TIME8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME 9.
        '''</summary>
        Friend Shared ReadOnly Property MIX_TIME9() As String
            Get
                Return ResourceManager.GetString("MIX_TIME9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING.
        '''</summary>
        Friend Shared ReadOnly Property MIXING() As String
            Get
                Return ResourceManager.GetString("MIXING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXER STEP.
        '''</summary>
        Friend Shared ReadOnly Property MIXSTEP() As String
            Get
                Return ResourceManager.GetString("MIXSTEP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TIME.
        '''</summary>
        Friend Shared ReadOnly Property MIXTIME() As String
            Get
                Return ResourceManager.GetString("MIXTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 1.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE1() As String
            Get
                Return ResourceManager.GetString("MIXTYPE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 10.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE10() As String
            Get
                Return ResourceManager.GetString("MIXTYPE10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 2.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE2() As String
            Get
                Return ResourceManager.GetString("MIXTYPE2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 3.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE3() As String
            Get
                Return ResourceManager.GetString("MIXTYPE3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 4.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE4() As String
            Get
                Return ResourceManager.GetString("MIXTYPE4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 5.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE5() As String
            Get
                Return ResourceManager.GetString("MIXTYPE5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 6.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE6() As String
            Get
                Return ResourceManager.GetString("MIXTYPE6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 7.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE7() As String
            Get
                Return ResourceManager.GetString("MIXTYPE7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 8.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE8() As String
            Get
                Return ResourceManager.GetString("MIXTYPE8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXING TYPE 9.
        '''</summary>
        Friend Shared ReadOnly Property MIXTYPE9() As String
            Get
                Return ResourceManager.GetString("MIXTYPE9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MIXER VOLUME.
        '''</summary>
        Friend Shared ReadOnly Property MIXVOL() As String
            Get
                Return ResourceManager.GetString("MIXVOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NAME.
        '''</summary>
        Friend Shared ReadOnly Property NAME() As String
            Get
                Return ResourceManager.GetString("NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NEW COMBINE.
        '''</summary>
        Friend Shared ReadOnly Property NEWCOMBINE() As String
            Get
                Return ResourceManager.GetString("NEWCOMBINE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NO.
        '''</summary>
        Friend Shared ReadOnly Property NO() As String
            Get
                Return ResourceManager.GetString("NO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No..
        '''</summary>
        Friend Shared ReadOnly Property No_() As String
            Get
                Return ResourceManager.GetString("No_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ORDER CODE.
        '''</summary>
        Friend Shared ReadOnly Property ORDERCODE() As String
            Get
                Return ResourceManager.GetString("ORDERCODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ENGLISH.
        '''</summary>
        Friend Shared ReadOnly Property rb_Eng() As String
            Get
                Return ResourceManager.GetString("rb_Eng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VIETNAMESE.
        '''</summary>
        Friend Shared ReadOnly Property rb_VNese() As String
            Get
                Return ResourceManager.GetString("rb_VNese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SAVE.
        '''</summary>
        Friend Shared ReadOnly Property SAVE() As String
            Get
                Return ResourceManager.GetString("SAVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VOLUME.
        '''</summary>
        Friend Shared ReadOnly Property VOLUME() As String
            Get
                Return ResourceManager.GetString("VOLUME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WEIGHING PROPERTIES.
        '''</summary>
        Friend Shared ReadOnly Property WEI_PRO() As String
            Get
                Return ResourceManager.GetString("WEI_PRO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to YES.
        '''</summary>
        Friend Shared ReadOnly Property YES() As String
            Get
                Return ResourceManager.GetString("YES", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
